### PR TITLE
[Nataliia Falinska] MoGo

### PR DESCRIPTION
**Pull request by NFalinska**

### CODE REVIEW

**Comment by NFalinska** [comment]
https://nfalinska.github.io/ui-internship-lwo2/css-practice/task_3/index.html

**Comment by tarasbobak** [comment]
What is this??? 
screen shot 2018-11-21 at 3 10 07 pm

**Comment by tarasbobak** [comment]
screen shot 2018-11-21 at 3 11 30 pm

**Comment by tarasbobak** [comment]
screen shot 2018-11-21 at 3 12 07 pm

**Comment by tarasbobak** [comment]
screen shot 2018-11-21 at 3 13 26 pm

**Comment by tarasbobak** [comment]
Never define font-size in vw

**Comment by tarasbobak** [comment]
Tablet is good, mobile is far from ideal

**Comment by tarasbobak** [comment]
Overly good, but you should work more

**Pull request merged**
