### PR TITLE
[stas-molchanov]CSS practice task 3

### PR DESCRIPTION
**Pull request by moskdev**

### CODE REVIEW

**Comment by moskdev** [comment]
https://moskdev.github.io/ui-internship-lwo2/css-practice/task-3/

**Comment by tarasbobak** [comment]
screen shot 2018-11-21 at 2 58 10 pm
missing

**Comment by tarasbobak** [comment]
Same on mobile.

**Comment by tarasbobak** [comment]
But actually it is possible that it would be hidden on mobile, same as instagram blocks :)

**Comment by tarasbobak** [comment]
Overly pretty good

**Comment by tarasbobak** [comment]
You should fix conflicts yourself

**Pull request merged**
