### PR TITLE
[Pavlo Turchyn] CSS-Task 3

### PR DESCRIPTION
**Pull request by FabianMoretti**

### CODE REVIEW

**Comment by FabianMoretti** [comment]
https://fabianmoretti.github.io/ui-internship-lwo2/css-practice/task_3/index.html

**Comment by tarasbobak** [comment]
+ For funny anumations

**Comment by tarasbobak** [comment]
Tablet looks pretty ugly 
screen shot 2018-11-22 at 10 47 29 am

Desktop and large screens is fine

**Comment by tarasbobak** [comment]
Mobile is also not very good. 
screen shot 2018-11-22 at 10 48 21 am

You don't feel yet how the markup should look like responsively.
You're not required though. It is what comes with practice.

**Pull request merged**
