### PR TITLE
[Nataliia Falinska] add-js-MoGo

### PR DESCRIPTION
**Pull request by NFalinska**
https://nfalinska.github.io/ui-internship-lwo2/task_3/index.html

### CODE REVIEW

**Comment by dverbovyi** [comment]
@NFalinska please resolve conflicts

**Comment by tarasbobak** [comment]
Sliders do not work at all for me.
Accordeon image does not change when you switch panels
When you open medusa image it is bigger than my screen size which is bad. Image should not take more than screen size when you are doing an image viewer

**Comment by tarasbobak** [comment]
I can't check js implementation as it is not working.
And I don't understand why do you have 112 files changed

**Comment by NFalinska** [comment]
> I can't check js implementation as it is not working.
> And I don't understand why do you have 112 files changed

I fixed bugs and created new branch https://github.com/griddynamics/ui-internship-lwo2/pull/203

**Comment by dverbovyi** [comment]
closed due to duplication https://github.com/griddynamics/ui-internship-lwo2/pull/203

**Pull request closed without merging**
